# your name (or website title) here
title: Raubins Raj 
logo: "/raubinsrajprofile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Senior Software Engineer
  <br><br>
  <a href="mailto:raubins.raj98@gmail.com">raubins.raj98@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/raubins-raj-18423214a/">LinkedIn Profile</a>
  <br>
  <a href="https://www.github.com/raubinsraj/">GitHub</a> 
theme: jekyll-theme-minimal
